[assembly: XmlnsDefinition("http://schemas.textilesystem.com/maui", "CommunityToolkit.Maui.Behaviors")]
[assembly: XmlnsDefinition("http://schemas.textilesystem.com/maui", "CommunityToolkit.Maui.Views")]
[assembly: XmlnsDefinition("http://schemas.textilesystem.com/maui", "CommunityToolkit.Maui.Core")]
[assembly: XmlnsDefinition("http://schemas.textilesystem.com/maui", "TextileSystem")]
[assembly: XmlnsDefinition("http://schemas.textilesystem.com/maui", "TextileSystem.Controls")]
[assembly: XmlnsDefinition("http://schemas.textilesystem.com/maui", "TextileSystem.ViewModels")]
[assembly: XmlnsDefinition("http://schemas.textilesystem.com/maui", "TextileSystem.MenuViewModels")]
[assembly: XmlnsDefinition("http://schemas.textilesystem.com/maui", "TextileSystem.Helpers")]
[assembly: XmlnsDefinition("http://schemas.textilesystem.com/maui", "TextileSystem.Models")]
[assembly: XmlnsPrefix("http://schemas.textilesystem.com/maui", "app")]


[assembly: XmlnsDefinition("http://schemas.syncfusion.com/maui", "Syncfusion.Maui.Core")]
[assembly: XmlnsDefinition("http://schemas.syncfusion.com/maui", "Syncfusion.Maui.Inputs")]
[assembly: XmlnsDefinition("http://schemas.syncfusion.com/maui", "Syncfusion.Maui.Popup")]
[assembly: XmlnsDefinition("http://schemas.syncfusion.com/maui", "Syncfusion.Maui.TabView")]
[assembly: XmlnsDefinition("http://schemas.syncfusion.com/maui", "Syncfusion.Maui.DataGrid")]
[assembly: XmlnsPrefix("http://schemas.syncfusion.com/maui", "sf")]